# TODO: Add Node.js base image

# TODO: Set working directory

# TODO: Copy package files

# TODO: Install dependencies

# TODO: Copy source code

# TODO: Build TypeScript

# TODO: Expose port

# TODO: Start application

